---
- name: Configure MacOS
  hosts: all

  vars_files:
    - vars/vars.yml

  tasks:
    - name: "MacOS base tasks"
      ansible.builtin.import_tasks: tasks/macos-base.yml
      tags: ['base']

    - name: "MacOS fonts"
      ansible.builtin.import_tasks: tasks/fonts.yml
      tags: ['fonts']
