---
- name: Download ComicMono.ttf
  ansible.builtin.get_url:
    url: https://dtinth.github.io/comic-mono-font/ComicMono.ttf
    dest: /tmp/ComicMono.ttf
    mode: "0644"

- name: Install ComicMono.ttf
  ansible.builtin.copy:
    src: /tmp/ComicMono.ttf
    dest: "/Users/{{ user_name }}/Library/Fonts/ComicMono.ttf"
    mode: "0644"

- name: Download ComicMono-Bold.ttf
  ansible.builtin.get_url:
    url: https://dtinth.github.io/comic-mono-font/ComicMono-Bold.ttf
    dest: /tmp/ComicMono-Bold.ttf
    mode: "0644"

- name: Install ComicMono-Bold.ttf
  ansible.builtin.copy:
    src: /tmp/ComicMono-Bold.ttf
    dest: "/Users/{{ user_name }}/Library/Fonts/ComicMono-Bold.ttf"
    mode: "0644"
